### 

POST http://localhost:8080/employee/save/ HTTP/1.1
Content-Type: application/json

{
 "id_employee": 1,
 "name_one": "Carlos",
 "other_name": "Fabian",
 "first_surname": "Corrales",
 "second_surname": "Zapata",
 "telephone": "3001234567",
 "address": "Calle 10 #20-30",
 "postcode": 630001,
 "email": "carloss@example.com",
 "city_name": "Armenia",
 "position_name": "Software Developer",
 "department_id":1
 }
